export {
  TOGGLE_DARK_MODE,
  toggleDarkMode,
  TOGGLE_NAV_BTNS_MENU,
  toggleNavBtnsMenu,
  CHANGE_COLORS,
  changeColors,
  CHANGE_SHADE,
  changeShade,
  SET_SNACKBAR_MESSAGE,
  setSnackbarMessage,
  HANDLE_SNACKBAR_CLOSE,
  handleSnackbarClose,
} from "./display.actions";
export {
  SET_CONTACT_NAME,
  setContactName,
  SET_CONTACT_MESSAGE,
  setContactMessage,
  SET_CONTACT_EMAIL,
  setContactEmail,
  SET_CONTACT_RATING,
  setContactRating,
  SET_CONTACT_BUGS,
  setContactBugs,
  SET_CONTACT_SUCCESS,
  setContactSuccess,
  SET_CONTACT,
  setContact,
} from "./contact.actions";
